#!/bin/bash

hostname=`vmtoolsd --cmd "info-get guestinfo.hostname"`
if [ $? -ne 0 ]
then
  hostname=vro-73-x86_64
fi

echo "Nice to meet you, my VM name is $hostname"

echo '- Setting local hostname...'

echo $hostname > /etc/HOSTNAME

hostname $hostname

echo "- Restarting network..."
service network restart

# Restarting the network service resets the hostname to
# its fqdn form, which is not what "info-get guestinfo.hostname"
# returns. We reset the hostname here so that vmpooler can detect
# this VM and move it to the ready queue.
hostname $hostname
